CONNECT TO ANNTEST;
SELECT INDSCHEMA, INDNAME, TABSCHEMA, TABNAME, COLNAMES FROM SYSCAT.INDEXES WHERE TABNAME = 'MEMBERS' OR INDNAME LIKE '%MEMBERS%' OR INDNAME LIKE '%NAME%UPPER%';
SELECT TABSCHEMA, TABNAME, TYPE FROM SYSCAT.TABLES WHERE TABNAME LIKE '%MEMBERS%' OR TABNAME LIKE '%NAME%UPPER%';
CONNECT RESET;
