CONNECT TO ANNTEST;
SELECT 'TABLE_OR_VIEW' AS TYPE, TABSCHEMA AS SCHEMA, TABNAME AS NAME, TYPE AS OBJECT_TYPE FROM SYSCAT.TABLES WHERE TABNAME = 'IDX_MEMBERS_NAME_UPPER_V1';
SELECT 'VIEW' AS TYPE, VIEWSCHEMA AS SCHEMA, VIEWNAME AS NAME, 'V' AS OBJECT_TYPE FROM SYSCAT.VIEWS WHERE VIEWNAME = 'IDX_MEMBERS_NAME_UPPER_V1';
SELECT 'INDEX' AS TYPE, INDSCHEMA AS SCHEMA, INDNAME AS NAME, UNIQUERULE AS OBJECT_TYPE FROM SYSCAT.INDEXES WHERE INDNAME = 'IDX_MEMBERS_NAME_UPPER_V1';
SELECT 'ALIAS' AS TYPE, TABSCHEMA AS SCHEMA, TABNAME AS NAME, TYPE AS OBJECT_TYPE FROM SYSCAT.TABLES WHERE TABNAME LIKE '%MEMBERS%NAME%UPPER%';
CONNECT RESET;
