-- Db2 LUW schema initialization.
CONNECT TO ANNTEST@
SET SCHEMA DB2INST1@

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
    EXECUTE IMMEDIATE 'DROP VIEW high_value_orders';
END@

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
    EXECUTE IMMEDIATE 'DROP TABLE staff_schedule';
    EXECUTE IMMEDIATE 'DROP TABLE staff';
    EXECUTE IMMEDIATE 'DROP TABLE services_weekly';
    EXECUTE IMMEDIATE 'DROP TABLE patients';
    EXECUTE IMMEDIATE 'DROP TABLE order_items';
    EXECUTE IMMEDIATE 'DROP TABLE orders';
    EXECUTE IMMEDIATE 'DROP TABLE products';
    EXECUTE IMMEDIATE 'DROP TABLE product_categories';
    EXECUTE IMMEDIATE 'DROP TABLE member_points_log';
    EXECUTE IMMEDIATE 'DROP TABLE members';
    EXECUTE IMMEDIATE 'DROP TABLE reserved_words_test';
    EXECUTE IMMEDIATE 'DROP TABLE multi_lang_i18n';
END@

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
    EXECUTE IMMEDIATE 'DROP SEQUENCE global_seq_id';
END@

CREATE TABLE members (
    member_id VARCHAR(30) NOT NULL,
    member_name VARCHAR(200),
    gender VARCHAR(10),
    birth_date DATE,
    phone VARCHAR(20),
    email VARCHAR(255),
    city VARCHAR(50),
    registration_date DATE,
    total_points INTEGER DEFAULT 0,
    last_login TIMESTAMP,
    created_at TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    updated_at TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (member_id)
)@

CREATE INDEX idx_members_city ON members(city)@
CREATE INDEX idx_members_name_upper ON members(UPPER(member_name))@

CREATE TABLE member_points_log (
    log_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_id VARCHAR(30) NOT NULL,
    points_change INTEGER NOT NULL,
    points_after INTEGER,
    reason VARCHAR(100),
    log_date DATE NOT NULL,
    PRIMARY KEY (log_id),
    CONSTRAINT fk_points_member FOREIGN KEY (member_id) REFERENCES members(member_id)
)@

CREATE TABLE product_categories (
    category_id VARCHAR(20) NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    parent_category VARCHAR(20),
    category_level INTEGER,
    description VARCHAR(500),
    PRIMARY KEY (category_id)
)@

CREATE TABLE products (
    product_id VARCHAR(20) NOT NULL,
    product_name VARCHAR(300) NOT NULL,
    category_id VARCHAR(20),
    price DECIMAL(12,2),
    cost_price DECIMAL(12,2),
    stock_quantity INTEGER DEFAULT 0,
    unit VARCHAR(20),
    status VARCHAR(20) DEFAULT 'active',
    created_date DATE,
    PRIMARY KEY (product_id),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES product_categories(category_id)
)@

CREATE INDEX idx_products_category ON products(category_id)@

CREATE TABLE orders (
    order_id VARCHAR(30) NOT NULL,
    member_id VARCHAR(30),
    order_date TIMESTAMP NOT NULL,
    total_amount DECIMAL(12,2),
    discount_amount DECIMAL(12,2) DEFAULT 0,
    actual_amount DECIMAL(12,2),
    order_status VARCHAR(20) DEFAULT 'pending',
    payment_method VARCHAR(20),
    shipping_city VARCHAR(50),
    remark VARCHAR(500),
    PRIMARY KEY (order_id),
    CONSTRAINT fk_order_member FOREIGN KEY (member_id) REFERENCES members(member_id)
)@

CREATE INDEX idx_orders_date ON orders(order_date)@
CREATE INDEX idx_orders_status ON orders(order_status)@

CREATE TABLE order_items (
    item_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id VARCHAR(30) NOT NULL,
    product_id VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (item_id),
    CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES products(product_id)
)@

CREATE TABLE patients (
    patient_id VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    age INTEGER,
    arrival_date DATE,
    departure_date DATE,
    service VARCHAR(30),
    satisfaction INTEGER,
    PRIMARY KEY (patient_id)
)@

CREATE INDEX idx_patients_service ON patients(service)@
CREATE INDEX idx_patients_age ON patients(age)@

CREATE TABLE services_weekly (
    week INTEGER NOT NULL,
    month INTEGER,
    service VARCHAR(30) NOT NULL,
    available_beds INTEGER,
    patients_request INTEGER,
    patients_admitted INTEGER,
    patients_refused INTEGER,
    patient_satisfaction INTEGER,
    staff_morale INTEGER,
    event VARCHAR(30),
    PRIMARY KEY (week, service)
)@

CREATE INDEX idx_services_month ON services_weekly(month)@
CREATE INDEX idx_services_event ON services_weekly(event)@

CREATE TABLE staff (
    staff_id VARCHAR(20) NOT NULL,
    staff_name VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL,
    service VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    updated_at TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (staff_id)
)@

CREATE INDEX idx_staff_role ON staff(role)@
CREATE INDEX idx_staff_service ON staff(service)@

CREATE TABLE staff_schedule (
    schedule_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    week INTEGER NOT NULL,
    staff_id VARCHAR(20) NOT NULL,
    staff_name VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL,
    service VARCHAR(30) NOT NULL,
    present SMALLINT,
    PRIMARY KEY (schedule_id)
)@

CREATE INDEX idx_schedule_week ON staff_schedule(week)@
CREATE INDEX idx_schedule_service ON staff_schedule(service)@

CREATE TABLE reserved_words_test (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "select" VARCHAR(100),
    "from" VARCHAR(100),
    "where" VARCHAR(100),
    "group" VARCHAR(100),
    "order" INTEGER,
    "user" VARCHAR(100),
    "type" VARCHAR(50),
    "default" VARCHAR(100),
    "values" VARCHAR(100),
    "table" VARCHAR(100),
    "index" VARCHAR(100),
    PRIMARY KEY (id)
)@

CREATE TABLE multi_lang_i18n (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(50) NOT NULL,
    entity_key VARCHAR(100) NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    content CLOB NOT NULL,
    remark VARCHAR(500),
    PRIMARY KEY (id),
    CONSTRAINT uk_entity_lang UNIQUE (entity_type, entity_key, lang_code)
)@

CREATE SEQUENCE global_seq_id
    START WITH 10000
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE
    CACHE 20@

CREATE VIEW high_value_orders AS
SELECT o.order_id, m.member_name, o.order_date, o.actual_amount
FROM orders o
INNER JOIN members m ON o.member_id = m.member_id
WHERE o.actual_amount > 1000@

SELECT 'DB2 LUW init.sql ready' AS status FROM SYSIBM.SYSDUMMY1@

CONNECT RESET@
TERMINATE@
